// <auto-generated />
using System;
using AudiobookPlanner.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudiobookPlanner.DataAccess.Data.Migrations
{
    [DbContext(typeof(AudiobookPlannerContext))]
    partial class AudiobookPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudiobookAuthors", b =>
                {
                    b.Property<int>("AudiobookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("AudiobookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("AudiobookAuthors", (string)null);
                });

            modelBuilder.Entity("AudiobookGenres", b =>
                {
                    b.Property<int>("AudiobookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("AudiobookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AudiobookGenres", (string)null);
                });

            modelBuilder.Entity("AudiobookLanguages", b =>
                {
                    b.Property<int>("AudiobookId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("AudiobookId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("AudiobookLanguages", (string)null);
                });

            modelBuilder.Entity("AudiobookNarrators", b =>
                {
                    b.Property<int>("AudiobookId")
                        .HasColumnType("int");

                    b.Property<int>("NarratorId")
                        .HasColumnType("int");

                    b.HasKey("AudiobookId", "NarratorId");

                    b.HasIndex("NarratorId");

                    b.ToTable("AudiobookNarrators", (string)null);
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Audiobook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LengthInMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Audiobooks");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Narrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Narrators");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("RatingAvg")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AudiobookRatings", b =>
                {
                    b.Property<int>("AudiobookId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("AudiobookId", "RatingId");

                    b.HasIndex("RatingId");

                    b.ToTable("AudiobookRatings", (string)null);
                });

            modelBuilder.Entity("AudiobookTags", b =>
                {
                    b.Property<int>("AudiobookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("AudiobookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("AudiobookTags", (string)null);
                });

            modelBuilder.Entity("AudiobookAuthors", b =>
                {
                    b.HasOne("AudiobookPlanner.DataAccess.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookAuthor_Audiobook");

                    b.HasOne("AudiobookPlanner.DataAccess.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookAuthor_Author");
                });

            modelBuilder.Entity("AudiobookGenres", b =>
                {
                    b.HasOne("AudiobookPlanner.DataAccess.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookGenre_Audiobook");

                    b.HasOne("AudiobookPlanner.DataAccess.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookGenre_Genre");
                });

            modelBuilder.Entity("AudiobookLanguages", b =>
                {
                    b.HasOne("AudiobookPlanner.DataAccess.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookLanguage_Audiobook");

                    b.HasOne("AudiobookPlanner.DataAccess.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookLanguage_Language");
                });

            modelBuilder.Entity("AudiobookNarrators", b =>
                {
                    b.HasOne("AudiobookPlanner.DataAccess.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookNarrator_Audiobook");

                    b.HasOne("AudiobookPlanner.DataAccess.Models.Narrator", null)
                        .WithMany()
                        .HasForeignKey("NarratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookNarrator_Narrator");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Audiobook", b =>
                {
                    b.HasOne("AudiobookPlanner.DataAccess.Models.Publisher", "Publisher")
                        .WithMany("Audiobooks")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudiobookPlanner.DataAccess.Models.Series", "Series")
                        .WithMany("Audiobooks")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Publisher");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("AudiobookRatings", b =>
                {
                    b.HasOne("AudiobookPlanner.DataAccess.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookRating_Audiobook");

                    b.HasOne("AudiobookPlanner.DataAccess.Models.Rating", null)
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookRating_Rating");
                });

            modelBuilder.Entity("AudiobookTags", b =>
                {
                    b.HasOne("AudiobookPlanner.DataAccess.Models.Audiobook", null)
                        .WithMany()
                        .HasForeignKey("AudiobookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookTag_Audiobook");

                    b.HasOne("AudiobookPlanner.DataAccess.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AudiobookTag_Tag");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Publisher", b =>
                {
                    b.Navigation("Audiobooks");
                });

            modelBuilder.Entity("AudiobookPlanner.DataAccess.Models.Series", b =>
                {
                    b.Navigation("Audiobooks");
                });
#pragma warning restore 612, 618
        }
    }
}
